# Generated by Django 3.0.3 on 2020-03-11 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafield',
            old_name='dataType',
            new_name='readingType',
        ),
    ]
