version: '3.3'

services:

#  data_controller:
#   container_name: data_controller
#   build: ./data_controller/
#   ports:
#    - "8801:8801"

  creation_api:
   container_name: creation_api
   build: ./creationAPI/
   ports:
    - "8803:8803"

  command_controller:
   container_name: command_controller
   build: ./commandController/
   ports:
    - "8802:8802"

  data_controller:
    container_name: data_controller
    build: ./dataController/
    ports:
      - "8801:8801"

#  db:
#   container_name: db
#   image: mysql:5.6
#   restart: always
#   environment:
#     MYSQL_ROOT_PASSWORD: example
#     MYSQL_USER: root
#     MYSQL_HOST: localhost
#     MYSQL_DATABASE: IoT
#   ports:
#     - "3306:3306"

  db:
    container_name: db
    build: ./DataBase/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: root
      MYSQL_HOST: localhost
      MYSQL_DATABASE: IoT
    ports:
      - "3306:3306"